#!/usr/bin/env python
# -*- coding:utf-8 -*-

import os
import re
import sys
import logging
import shutil
import datetime
import subprocess
import ConfigParser
import getpass
import yaml

from argparse import ArgumentParser

try:
    import caliper.common as common
except ImportError:
    import common

from caliper.server.build import build
from caliper.server.run import run
from caliper.server.run import parser_log
from caliper.server.run import score
from caliper.server.run import write_results
from caliper.server.shared.settings import settings
from caliper.server.hosts import host_factory
from caliper.server.shared import caliper_path
from caliper.server.shared import send_mails
from caliper.server import summary
from caliper.server.parser_process import parser as parser_engine
from caliper.server.parser_process import normalize
from caliper.server.shared.caliper_path import intermediate
from caliper.server.shared.caliper_path import folder_ope as Folder
from caliper.server.upload import upload


def build_all_tests(test_node, remote_host,f_option,clear, sections):
    try:
        logging.info("Begining to build Caliper for the remote host")
        result1 = build.build_for_target(test_node, remote_host, f_option, clear, sections)
    except Exception, e:
        logging.info(e)
        raise
    else:
        return result1

def run_caliper(test_node, f_option, sections, run_case_list, num):
    try:
        logging.debug("begining to run Caliper")
        result = run.run_caliper_tests(test_node, f_option, sections, run_case_list, num)
    except Exception, e:
        print e
        logging.info("There is wrong when running Caliper")
        raise
    else:
        return result

def parser_caliper_logs(f_option, sections, run_case_list):
    try:
        logging.debug("begining to Parse Caliper Logs")
        result = parser_log.parser_caliper_tests(f_option, sections, run_case_list)
    except Exception, e:
        print e
        logging.info("There is wrong when parsing Caliper")
        raise
    else:
        return result

def parser_caliper(remote_host):
    try:
        logging.debug("begining to parser the result of caliper")
        parser_engine.parser_caliper(remote_host)
    except Exception, e:
        logging.info("There is wrong when parsering the caliper result")
        raise

def upload_url(result_path):
    '''
    upload test result to caliper server
    :param result_path: the result path
    :return: none
    '''
    try:
        server_num = settings.get_value('Caliperweb', 'server_num', type=int)
    except Exception, e:
        server_num = 0
    for i in range(server_num):
        try:
            server_ip = settings.get_value('Caliperweb', 'server_ip%s' % int(i+1), type=str)
        except Exception, e:
            server_ip = None
        try:
            server_user = settings.get_value('Caliperweb', 'server_user%s' % int(i+1), type=str)
        except Exception, e:
            server_user = ""

        try:
            server_password = settings.get_value('Caliperweb', 'server_password%s' % int(i+1), type=str)
        except Exception, e:
            server_password = ""
        print server_ip
        if server_ip:
            try:
                server_ip += ':8000'
                logging.info("remote server %s upload start" % server_ip)
                upload.upload_result(result_path, server_ip, server_user, server_password)
                logging.info("remote upload end")
            except Exception as e:
                logging.info(e)
    if server_num == 0:
        logging.info('no upload value,please set upload value at caliper_output/configuration/config/client_config.cfg file')

def get_remote_host():
    '''
    get test host
    :return: host info
    '''
    cf = ConfigParser.ConfigParser()
    host_path = os.path.join(caliper_path.config_files.config_dir, 'hosts')
    cf.read(host_path)
    sections = cf.sections()
    opts = cf.options(sections[0])[0].split(' ')
    client_ip = opts[0]
    user_list = cf.get(sections[0], cf.options(sections[0])[0])
    user = user_list.split(' ')[0]
    port = 22
    password = user_list.split('"')[-2]
    remote_host = host_factory.create_host(client_ip, user, password, port)
    return remote_host

def normalize_scores():
    write_results.yaml_filter(Folder.yaml_dir)
    return

def read_config():
    '''
    :return: tool list and run case list
    '''
    config_files = os.path.join(caliper_path.config_files.config_dir, 'cases_config.json')
    fp = open(config_files, 'r')
    tool_list = []
    run_case_list = []
    case_list = yaml.load(fp.read())
    for dimension in case_list:
        for i in range(len(case_list[dimension])):
            for tool in case_list[dimension][i]:
                for case in case_list[dimension][i][tool]:
                    if case_list[dimension][i][tool][case][0] == 'enable':
                        tool_list.append(tool)
                        run_case_list.append(case)
    sections = list(set(tool_list))
    return sections, run_case_list

def get_config(con):
    '''
    :return: tool list and run case list
    '''
    config_files = os.path.join(caliper_path.config_files.config_dir, 'cases_config.json')
    fp = open(config_files, 'r')
    tool_list = []
    run_case_list = []
    case_list = yaml.load(fp.read())
    dimension_list = case_list.keys()
    sections = []
    if con !='':
        if '.yml' in con:
            sections.append(con.split('_')[0])
            run_case_list.append(con.split('.yml')[0])
        elif con in dimension_list:
            for i in range(len(case_list[con])):
                for tool in case_list[con][i]:
                    for case in case_list[con][i][tool]:
                        tool_list.append(tool)
                        run_case_list.append(case)
            sections = list(set(tool_list))
        else:
            sections.append(con)
            for dimension in dimension_list:
                for i in range(len(case_list[dimension])):
                    try:
                        for case in case_list[dimension][i][con]:
                            run_case_list.append(case)
                    except:
                        pass
    else:
        sections, run_case_list = read_config()
    return sections, run_case_list

def push_ssh_key():
    '''
    use ansible push ssh key to test host
    :return: 
    '''
    TEST_CASE_DIR = caliper_path.config_files.config_dir
    ssh_key_path = os.path.join(os.environ['HOME'], '.ssh', 'id_rsa.pub')
    if not os.path.exists(ssh_key_path):
        os.system("ssh-keygen -t rsa -P '' -f '%s/.ssh/id_rsa'"% os.environ['HOME'])
    try:
        logging.info('Begining to push ssh key for the test host')
        os.chdir(TEST_CASE_DIR)
        subprocess.call('ansible-playbook -i hosts push_sshkey.yml -u %s' % getpass.getuser(), stdout=subprocess.PIPE, shell=True)
    except Exception as e:
        logging.debug(e)
        logging.info('push ssh key fail')
        pass

if __name__=="__main__":
    parser = ArgumentParser(version=common.VERSION)
    parser.add_argument("-a", "--all", action="store_true", dest="all", default=False, help="run all")
    parser.add_argument("-b", "--build", action="store_true",
            dest="build", default=False,help="select to incrementally build the selected test tools")
    parser.add_argument("-c", "--cleanbuild", action="store_true",
            dest="cleanbuild", help="select to clean build the selected tools")
    parser.add_argument("-r", "--run", action="store", dest="run", default="", help="select to run the selected test tools")
    parser.add_argument("-p", "--parse", action="store_true", dest="parse", default=False,
                        help="select to Parse the selected test tools")
    parser.add_argument("-s", "--score", action="store_true", dest="score", default=False,
                        help="select to Score the selected test tools")
    parser.add_argument("-u", "--upload", action="store_true", dest="upload", default=False,
            help="select the webpage to upload")
    parser.add_argument("-e", "--email", action="store_true", dest="send_email",
            default=False, help="Select to send mail to the receivers or not")
    parser.add_argument( "-f", "--folder", action="store", dest="folder",
            default="", help="assign a folder to store the results")
    parser.add_argument("-l", "--benchmarklist", action="store_true", dest="benchmarklist", default=False,
                        help="display support benchmark list")
    parser.add_argument("-d", "--debug", action="store_true", dest="debug", default=False,help="debug mode")
    parser.add_argument("-m", "--message", action="store", dest="message",default="", help="add a message for test")
    parser.add_argument("-t", "--times", action="store", dest="times", default="", help="test times")
    parser.add_argument("-n", "--node", action="store", dest="node", default="", help="Select testnode to run test")

    args = parser.parse_args()
    start_time = datetime.datetime.now()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    config_files = os.path.join(caliper_path.config_files.config_dir, 'cases_config.json')
    fp = open(config_files, 'r')
    tool_list = []
    case_list = yaml.load(fp.read())
    dimension_list = {}
    for dimension in case_list:
        dimension_list[dimension] = []
        for i in range(len(case_list[dimension])):
            for tool in case_list[dimension][i]:
                dimension_list[dimension].append(tool)
    if args.benchmarklist:
        for dimen in dimension_list:
            print dimen + ':'
            for tool in dimension_list[dimen]:
                print '    '+tool
        sys.exit()

    f_option = 0
    if args.folder:
        f_option = 1
        caliper_path.folder_ope.workspace = args.folder
        caliper_path.folder_ope.set_up_path()
        from caliper.server.shared.caliper_path import folder_ope as FOLDER
        if os.path.exists(FOLDER.caliper_log_file):
            fp = open(FOLDER.caliper_log_file,'a+')
            fp.write("re-execution with -f .It may be execution of all the tools or some specific tools as specified in the config file \n")
            fp.close()
    if not os.path.exists(caliper_path.folder_ope.workspace):
        try:
            os.makedirs(caliper_path.folder_ope.workspace)
        except Exception as e:
            print e
            sys.exit(1)

    # get config file
    caliper_path.config_files.name = caliper_path.folder_ope.workspace
    caliper_path.config_files.setup_path()
    if not os.path.exists(caliper_path.folder_ope.workspace + "/config"):
        shutil.copytree(caliper_path.caliper_config_file, caliper_path.folder_ope.workspace + "/config")

    settings.set_config_files(os.path.join(
        caliper_path.config_files.config_dir,
        'client_config.cfg'
    ))

    # create test dir
    caliper_path.create_dir()
    remote_host = get_remote_host()
    num = 0
    if args.times:
        num = int(args.times)
    test_node = ''
    if args.node:
        test_node = args.node
    if args.all:
        sections, run_case_list = get_config('')
        push_ssh_key()
        # build
        try:
            clear = 0
            if args.cleanbuild:
                clear = 1
            result1 = build_all_tests(test_node, remote_host, f_option, clear, sections)
            if result1:
                sys.exit()
        except Exception, e:
            raise
        # run
        try:
            result2 = run_caliper(test_node, f_option, sections, run_case_list, num)
            if result2:
                sys.exit()

        except Exception:
            raise

        end_time = datetime.datetime.now()
        interval = end_time - start_time
        try:
            summary_path = os.path.join(caliper_path.folder_ope.workspace, 'output', 'results_summary.log')
            summary.output_summary_info(remote_host, summary_path, interval.seconds)
        except Exception, e:
            raise e
        # parser
        try:
            result2 = parser_caliper_logs(f_option, sections, run_case_list)
            if result2:
               sys.exit()
            result2 = score.compute_caliper_logs(sections, run_case_list,1)
        except Exception:
            raise
        # score
        try:
            result2 = score.compute_caliper_logs(sections, run_case_list,2)
            if intermediate:
                parser_caliper(remote_host)
        except Exception as e:
            print e
            pass
        # upload
        try:
            # filter all the test cases to get only the common test cases passed in all the plaforms. other test cases marked as INVALID.
            flag = normalize_scores()

            # Reads one value from all the plaforms and then compares this values with each other to rank them. This is done for all the values in the yaml files. These new values are writed to _score_post.yaml.
            write_results.normalize_caliper()

            # computes the score i.e TOTAL_SCORE in the form of 100% for each section in the newly generated _post.yaml and _post.json files. _post.yaml file is to be used for image creation and _post.json file is to be used for table creation in HTML report.
            normalize.normalise()
        except Exception as e:
            print e
        try:
            upload_url(caliper_path.folder_ope.workspace)
        except:
            pass

    if args.build or args.run:
        push_ssh_key()
        if args.build:
            sections, run_case_list = get_config(args.build)
            try:
                clear = 0
                if args.cleanbuild:
                    clear = 1
                result1 = build_all_tests(test_node, remote_host,f_option,clear, sections)
                if result1:
                    sys.exit()
            except Exception, e:
                raise

        if args.run:
            sections, run_case_list = get_config(args.run)
            try:
                result2 = run_caliper(test_node, f_option, sections, run_case_list, num)
                if result2:
                    sys.exit()

            except Exception:
                raise

            end_time = datetime.datetime.now()
            interval = end_time - start_time
            try:
                summary_path = os.path.join(caliper_path.folder_ope.workspace, 'output', 'results_summary.log')
                summary.output_summary_info(remote_host, summary_path, interval.seconds)
            except Exception, e:
                raise e

    if args.parse:
        sections, run_case_list = get_config('')
        try:
            result2 = parser_caliper_logs(f_option, sections, run_case_list)
            if result2:
               sys.exit()
            result2 = score.compute_caliper_logs(sections, run_case_list,1)
        except Exception:
            raise
    if args.score:
        sections, run_case_list = get_config('')
        try:
            result2 = score.compute_caliper_logs(sections, run_case_list,2)
            if intermediate:
                parser_caliper(remote_host)
        except Exception as e:
            print e
            pass

    if args.upload:
        try:
            # copy_yaml(remote_host)
            # filter all the test cases to get only the common test cases passed in all the plaforms. other test cases marked as INVALID.
            flag = normalize_scores()

            # Reads one value from all the plaforms and then compares this values with each other to rank them. This is done for all the values in the yaml files. These new values are writed to _score_post.yaml.
            write_results.normalize_caliper()

            # computes the score i.e TOTAL_SCORE in the form of 100% for each section in the newly generated _post.yaml and _post.json files. _post.yaml file is to be used for image creation and _post.json file is to be used for table creation in HTML report.

            normalize.normalise()
        except Exception as e:
            print e
        try:
            upload_url(caliper_path.folder_ope.workspace)
        except:
            pass
    result_name = caliper_path.folder_ope.workspace.split(os.sep)[-1] + '.zip'
    result_path = caliper_path.CALIPER_REPORT_HOME
    if args.upload and args.send_email:
        result_path = os.path.join(result_path, result_name)
        if os.path.exists(result_path):
            send_mails.send_mails(result_path)
            print("\n'%s file has been sent, please check the mail\n" % result_name)
            sys.exit()
        if not os.path.exists(result_path):
            try:
                os.makedirs(caliper_path.folder_ope.workspace)
            except Exception as e:
                print("\nCan't able to send the mail as '%s' file is not created\n" % result_name)
                sys.exit()

    if args.message:
        message_file = Folder.caliper_message_file
        mp = open(message_file, 'a+')
        mp.write(args.message)

    if args.folder and args.send_email:
        result_path = os.path.join(caliper_path.folder_ope.workspace, caliper_path.folder_ope.name,
                                   'results_summary.log')
        if os.path.exists(result_path):
             send_mails.send_mails(result_path)
             print("\n'results_summary.log' file has been sent, please check the mail\n")
             sys.exit()
        if not os.path.exists(result_path):
            try:
                os.makedirs(caliper_path.folder_ope.workspace)
            except Exception as e:
                print("\nCan't able to send the mail as 'results_summary.log' file is not present\n ")
                sys.exit()

    if not args.folder and args.send_email:
        result_path = os.path.join(caliper_path.folder_ope.workspace, caliper_path.folder_ope.name,
                                   'results_summary.log')
        if os.path.exists(result_path):
            send_mails.send_mails(result_path)
            print("\n'results_summary.log' file has been sent , please check the mail\n")
            sys.exit()
        if not os.path.exists(result_path):
            try:
                os.makedirs(caliper_path.folder_ope.workspace)
            except Exception as e:
                print("\n Can't able to send the mail as 'results_summary.log' file is not present\n ")
                sys.exit()

    if not args.upload and args.send_email:
        current_path = os.getcwd()
        flag = 0
        for root, _, files in sorted(os.walk(current_path)):
            for name in files:
                if re.search(result_name, name):
                    result_path = os.path.join(root, name)
                    flag = 1
                    break
            if flag == 1:
                break
        if os.path.exists(result_path):
            send_mails.send_mails(result_path)

