- name: install numactl for redhat
  yum: name=numactl state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: install numactl for ubuntu
  apt: name=numactl state=present
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: install numactl for CentOS
  yum: name=numactl state=present disable_gpg_check=yes
  when: ansible_distribution == 'CentOS'
  ignore_errors: yes

- name: install numactl for Debian
  apt: name=numactl state=present
  when: ansible_distribution == 'Debian'
  ignore_errors: yes

- name: install numactl for SLES
  zypper: name=numactl state=present
  when: ansible_distribution == 'SLES'
  ignore_errors: yes

- name: create speccpu2006 directory
  file: path={{ lmbench_locate }} state=directory mode=0755

- name: copy file
  copy: src=lmbench-3.0-a9.tgz dest=/usr/local/benchmark mode=0777

- name: Decompress lmbench tarball
  unarchive:
    src={{ lmbench_locate }}/lmbench-3.0-a9.tgz
    dest={{ lmbench_locate }}/
    copy=yes
    list_files=yes

- name: copy scripts to targetpath
  copy: src=scripts dest={{ lmbench_home }}/ mode=0755 
  tags: cc

- name: build lmbench
  shell: ./lmbench-build.sh
  args:
    chdir: /usr/local/benchmark/lmbench-3.0-a9/scripts
  
